# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'RevenueCatUIProxy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RevenueCatUIProxy
  pod 'RevenueCat', '4.39.0'
  pod 'RevenueCatUI', '4.39.0'
end
