# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'RevenueCatUIProxy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RevenueCatUIProxy
  pod 'RevenueCat'
  pod 'RevenueCatUI'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['RevenueCat', 'RevenueCatUI'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.10'  # The swift version you are using
      end
    end
  end
end